In [23]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from matplotlib.colors import ListedColormap

In [24]:
dataset = pd.read_csv('Social_Network_Ads.csv')

In [25]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
7    15694829  Female   32           150000          1
8    15600575    Male   25            33000          0
9    15727311  Female   35            65000          0
10   15570769  Female   26            80000          0
11   15606274  Female   26            52000          0
12   15746139    Male   20            86000          0
13   15704987    Male   32            18000          0
14   15628972    Male   18            82000          0
15   15697686    Male   29            80000          0
16   15733883    Male   47            25000          1
17   15617482    Male   45            26000          1
18   15704583    Male   46            28000          1
19   15621083  Female   48            29000          1
20   15649487    Male   45            22000          1
21   15736760  Female   47            49000          1
22   15714658    Male   48            41000          1
23   15599081  Female   45            22000          1
24   15705113    Male   46            23000          1
25   15631159    Male   47            20000          1
26   15792818    Male   49            28000          1
27   15633531  Female   47            30000          1
28   15744529    Male   29            43000          0
29   15669656    Male   31            18000          0
..        ...     ...  ...              ...        ...
370  15611430  Female   60            46000          1
371  15774744    Male   60            83000          1
372  15629885  Female   39            73000          0
373  15708791    Male   59           130000          1
374  15793890  Female   37            80000          0
375  15646091  Female   46            32000          1
376  15596984  Female   46            74000          0
377  15800215  Female   42            53000          0
378  15577806    Male   41            87000          1
379  15749381  Female   58            23000          1
380  15683758    Male   42            64000          0
381  15670615    Male   48            33000          1
382  15715622  Female   44           139000          1
383  15707634    Male   49            28000          1
384  15806901  Female   57            33000          1
385  15775335    Male   56            60000          1
386  15724150  Female   49            39000          1
387  15627220    Male   39            71000          0
388  15672330    Male   47            34000          1
389  15668521  Female   48            35000          1
390  15807837    Male   48            33000          1
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [26]:
X = dataset.iloc[:,[2,3]].values
y = dataset.iloc[:, 4].values

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=0)

In [28]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)

D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [29]:
X_train

array([[ 0.58164944, -0.88670699],
       [-0.60673761,  1.46173768],
       [-0.01254409, -0.5677824 ],
       [-0.60673761,  1.89663484],
       [ 1.37390747, -1.40858358],
       [ 1.47293972,  0.99784738],
       [ 0.08648817, -0.79972756],
       [-0.01254409, -0.24885782],
       [-0.21060859, -0.5677824 ],
       [-0.21060859, -0.19087153],
       [-0.30964085, -1.29261101],
       [-0.30964085, -0.5677824 ],
       [ 0.38358493,  0.09905991],
       [ 0.8787462 , -0.59677555],
       [ 2.06713324, -1.17663843],
       [ 1.07681071, -0.13288524],
       [ 0.68068169,  1.78066227],
       [-0.70576986,  0.56295021],
       [ 0.77971394,  0.35999821],
       [ 0.8787462 , -0.53878926],
       [-1.20093113, -1.58254245],
       [ 2.1661655 ,  0.93986109],
       [-0.01254409,  1.22979253],
       [ 0.18552042,  1.08482681],
       [ 0.38358493, -0.48080297],
       [-0.30964085, -0.30684411],
       [ 0.97777845, -0.8287207 ],
       [ 0.97777845,  1.8676417 ],
       [-0.01254409,

In [30]:
classifier = LogisticRegression(random_state=0)

In [31]:
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [32]:
y_pred = classifier.predict(X_test)

In [33]:
cm = confusion_matrix(y_test, y_pred)

In [34]:
cm

array([[63,  5],
       [ 7, 25]], dtype=int64)

In [38]:
X_set, y_set = X_train, y_train

In [72]:
np.arange(start = X_set[:, 0].min()-1, stop = X_set[:, 0].max()+1 , step = .01)

array([-2.60035469e+00, -2.59035469e+00, -2.58035469e+00, -2.57035469e+00,
       -2.56035469e+00, -2.55035469e+00, -2.54035469e+00, -2.53035469e+00,
       -2.52035469e+00, -2.51035469e+00, -2.50035469e+00, -2.49035469e+00,
       -2.48035469e+00, -2.47035469e+00, -2.46035469e+00, -2.45035469e+00,
       -2.44035469e+00, -2.43035469e+00, -2.42035469e+00, -2.41035469e+00,
       -2.40035469e+00, -2.39035469e+00, -2.38035469e+00, -2.37035469e+00,
       -2.36035469e+00, -2.35035469e+00, -2.34035469e+00, -2.33035469e+00,
       -2.32035469e+00, -2.31035469e+00, -2.30035469e+00, -2.29035469e+00,
       -2.28035469e+00, -2.27035469e+00, -2.26035469e+00, -2.25035469e+00,
       -2.24035469e+00, -2.23035469e+00, -2.22035469e+00, -2.21035469e+00,
       -2.20035469e+00, -2.19035469e+00, -2.18035469e+00, -2.17035469e+00,
       -2.16035469e+00, -2.15035469e+00, -2.14035469e+00, -2.13035469e+00,
       -2.12035469e+00, -2.11035469e+00, -2.10035469e+00, -2.09035469e+00,
       -2.08035469e+00, -

In [39]:
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min()-1, stop = X_set[:, 0].max()+1, step = .01),
                     np.arange(start = X_set[:, 1].min()-1, stop = X_set[:, 1].max()+1, step = .01))

In [69]:
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set [y_set == j, 0], X_set [y_set == j, 1],
               c = ListedColormap(('red', 'green'))(i), label =j)
plt.title("Logistic Regression(Training Set)")
plt.xlabel("Age")
plt.ylabel("Expected Salary")
plt.legend()
plt.rcParams['figure.figsize'] = [15,6]
plt.show()

In [70]:
X_set, y_set = X_test, y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min()-1, stop = X_set[:, 0].max()+1 , step = .01),
                     np.arange(start = X_set[:, 1].min()-1, stop = X_set[:, 1].max()+1, step = .01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set [y_set == j, 0], X_set [y_set == j, 1],
               c = ListedColormap(('red', 'green'))(i), label =j)
plt.title("Logistic Regression (Test Set)")
plt.xlabel("Age")
plt.ylabel("Expected Salary")
plt.legend()
plt.rcParams['figure.figsize'] = [15,6]
plt.show()

In [75]:
X1.shape

(613, 569)