In [76]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import keras
from keras.models import Sequential
from keras.layers import Dense

In [53]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [54]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [55]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [56]:
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

In [57]:
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [58]:
X[0]

array([619, 0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [59]:
onehotencoder = OneHotEncoder(categorical_features= [1])
X = onehotencoder.fit_transform(X).toarray()

In [60]:
X[0]

array([1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
       0.0000000e+00, 4.2000000e+01, 2.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05])

In [61]:
X = X[:, 1:]

In [62]:
X[0]

array([0.0000000e+00, 0.0000000e+00, 6.1900000e+02, 0.0000000e+00,
       4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0134888e+05])

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [64]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [65]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [66]:
classifier = Sequential()

In [68]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [69]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [70]:
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [71]:
classifier.compile(optimizer='adam', loss= 'binary_crossentropy', metrics=['accuracy'])

In [72]:
classifier.fit(X_train, y_train, batch_size = 10, epochs=100)

Epoch 1/100
8000/8000 [==============================] - 24s 3ms/step - loss: 0.4903 - acc: 0.7950
Epoch 2/100
8000/8000 [==============================] - 4s 440us/step - loss: 0.4305 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 3s 377us/step - loss: 0.4257 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 3s 353us/step - loss: 0.4206 - acc: 0.8154
Epoch 5/100
8000/8000 [==============================] - 3s 355us/step - loss: 0.4180 - acc: 0.8250
Epoch 6/100
8000/8000 [==============================] - 3s 357us/step - loss: 0.4158 - acc: 0.8292
Epoch 7/100
8000/8000 [==============================] - 3s 346us/step - loss: 0.4138 - acc: 0.8319
Epoch 8/100
8000/8000 [==============================] - 3s 346us/step - loss: 0.4124 - acc: 0.8310
Epoch 9/100
8000/8000 [==============================] - 3s 344us/step - loss: 0.4109 - acc: 0.8317
Epoch 10/100
8000/8000 [==============================] - 3s 344us/step - loss: 0.4100 - acc: 0.8315


Epoch 82/100
8000/8000 [==============================] - 3s 364us/step - loss: 0.4008 - acc: 0.8355
Epoch 83/100
8000/8000 [==============================] - 3s 363us/step - loss: 0.4004 - acc: 0.8350
Epoch 84/100
8000/8000 [==============================] - 3s 363us/step - loss: 0.4002 - acc: 0.8365
Epoch 85/100
8000/8000 [==============================] - 3s 364us/step - loss: 0.4004 - acc: 0.8355
Epoch 86/100
8000/8000 [==============================] - 3s 364us/step - loss: 0.4002 - acc: 0.8357
Epoch 87/100
8000/8000 [==============================] - 3s 361us/step - loss: 0.4000 - acc: 0.8351
Epoch 88/100
8000/8000 [==============================] - 3s 362us/step - loss: 0.4005 - acc: 0.8359
Epoch 89/100
8000/8000 [==============================] - 3s 361us/step - loss: 0.4003 - acc: 0.8371
Epoch 90/100
8000/8000 [==============================] - 3s 369us/step - loss: 0.4002 - acc: 0.8352
Epoch 91/100
8000/8000 [==============================] - 3s 363us/step - loss: 0.4002 - ac

In [73]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [74]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [77]:
cm = confusion_matrix(y_test, y_pred)

In [78]:
cm

array([[1551,   44],
       [ 275,  130]], dtype=int64)