In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [3]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [5]:
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

In [6]:
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [7]:
X[0]

array([619, 0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [8]:
onehotencoder = OneHotEncoder(categorical_features= [1])
X = onehotencoder.fit_transform(X).toarray()

In [9]:
X[0]

array([1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
       0.0000000e+00, 4.2000000e+01, 2.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05])

In [10]:
X = X[:, 1:]

In [11]:
X[0]

array([0.0000000e+00, 0.0000000e+00, 6.1900000e+02, 0.0000000e+00,
       4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0134888e+05])

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [13]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [14]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [15]:
classifier = Sequential()

In [16]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [17]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [18]:
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [19]:
classifier.compile(optimizer='adam', loss= 'binary_crossentropy', metrics=['accuracy'])

In [20]:
classifier.fit(X_train, y_train, batch_size = 10, epochs=100)

Epoch 1/100
8000/8000 [==============================] - 4s 486us/step - loss: 0.4905 - acc: 0.7951: 7s - lo
Epoch 2/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.4272 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.4222 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 115us/step - loss: 0.4185 - acc: 0.8176
Epoch 5/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4155 - acc: 0.8275
Epoch 6/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4137 - acc: 0.8299
Epoch 7/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4123 - acc: 0.8317
Epoch 8/100
8000/8000 [==============================] - 1s 121us/step - loss: 0.4114 - acc: 0.8307
Epoch 9/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4098 - acc: 0.8339
Epoch 10/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4090 - ac

8000/8000 [==============================] - 1s 64us/step - loss: 0.4000 - acc: 0.8356
Epoch 83/100
8000/8000 [==============================] - 1s 65us/step - loss: 0.3997 - acc: 0.8355
Epoch 84/100
8000/8000 [==============================] - 1s 64us/step - loss: 0.4004 - acc: 0.8345
Epoch 85/100
8000/8000 [==============================] - 1s 64us/step - loss: 0.4005 - acc: 0.8336
Epoch 86/100
8000/8000 [==============================] - 1s 65us/step - loss: 0.3995 - acc: 0.8352
Epoch 87/100
8000/8000 [==============================] - 1s 64us/step - loss: 0.4003 - acc: 0.8352
Epoch 88/100
8000/8000 [==============================] - 1s 64us/step - loss: 0.4000 - acc: 0.8352
Epoch 89/100
8000/8000 [==============================] - 1s 72us/step - loss: 0.4000 - acc: 0.8344
Epoch 90/100
8000/8000 [==============================] - 1s 66us/step - loss: 0.4004 - acc: 0.8369
Epoch 91/100
8000/8000 [==============================] - 1s 68us/step - loss: 0.4003 - acc: 0.8360
Epoch 92/100


In [22]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [23]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [24]:
cm = confusion_matrix(y_test, y_pred)

In [25]:
cm

array([[1549,   46],
       [ 274,  131]], dtype=int64)